apiVersion: v1
kind: ServiceAccount
metadata:
  name: airflow-operator
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: airflow-operator-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - "pods"
  - "services"
  verbs:
  - "create"
  - "delete"
  - "get"
  - "list"
  - "patch"
  - "update"
  - "watch"
- apiGroups:
  - ""
  resources:
  - "pods/exec"
  - "pods/log"
  verbs:
  - "create"
  - "get"
  - "list"
  - "watch"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airflow-operator-rolebinding
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: airflow-operator
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: airflow-operator-role
  apiGroup: rbac.authorization.k8s.io
